### PR TITLE
feat(vite-plugin): support glob for project files

### PR DESCRIPTION
**Pull request by rmhartog**
Adopting the stale pull request #576 because it failed CI.

Support glob patterns for project files in the vite-plugin.

Please credit @guifeliper as below if squash-merging.

Closes: #324
Co-Authored-By: Guilherme Reis <guifeliper@gmail.com>

### CODE REVIEW

**Comment by aarthificial** [comment]
Can we use [`fast-glob`](https://www.npmjs.com/package/fast-glob) instead of `glob`?

**Comment by rmhartog** [comment]
> Can we use [`fast-glob`](https://www.npmjs.com/package/fast-glob) instead of `glob`?

Looks like that'd be a simple replacement, will pick that up soon.

**Comment by rmhartog** [comment]
Updated to `fast-glob`, let me know what you think @aarthificial :)

**Comment by aarthificial** [comment]
Could you also update the TSDoc comments and [the documentation](https://motioncanvas.io/docs/configuration#project) to mention the support for globs?

**Comment by rmhartog** [comment]
> Could you also update the TSDoc comments and [the documentation](https://motioncanvas.io/docs/configuration#project) to mention the support for globs?

Do you think mentioning support like I did for now is sufficient?

**Comment by aarthificial** [comment]
Yes, thanks!

**Pull request merged**
