### PR TITLE
feat(ui): add color picker popover to color input

### PR DESCRIPTION
**Pull request by jmaen**
Add a color picker popover to the color input component. It can be opened by clicking the color preview.

grafik

### CODE REVIEW

**Comment by jmaen** [comment]
Is there something that you want me to change @aarthificial ?

**Comment by aarthificial** [comment]
Apologies, I got distracted by the next release.
I pushed a tiny commit with some style adjustments to make the color input consistent with the input select (the color box is now a separate button):
image

Other than that the only problem left is the fact that the width of scrollbars is different on Chrome than on Firefox which makes the picker misaligned on Chrome:
image

**Comment by jmaen** [comment]
No worries :) The alignment shoult be fixed now.

**Review by aarthificial — APPROVED** [review]

**Comment by aarthificial** [comment]
Awesome, thanks!

**Pull request merged**
